services:
  redis-server:
    container_name: notification-Redis
    image: "redis:8.4-alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    container_name: notification-FastAPI
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  test:
    container_name: notification-pytest
    build: .
    depends_on:
      - app
    command: >
      sh -c "
        echo 'ğŸ§ª Ğ—Ğ°Ğ¿ÑƒÑĞº Ñ‚ĞµÑÑ‚Ğ¾Ğ²...' &&
        pytest -x --tb=short
      "

volumes:
  redis_data:
    driver: local
